// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Hob63kxbSkGLuIfT--SsiT-fwo4J-_M',
    appId: '1:309888173927:web:a1fbab6204043bf8a511c2',
    messagingSenderId: '309888173927',
    projectId: 'tharu-bag-center',
    authDomain: 'tharu-bag-center.firebaseapp.com',
    storageBucket: 'tharu-bag-center.firebasestorage.app',
    measurementId: 'G-HQ96GY0Y1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnHw2Gmj-OFk6y0Su4djVhwZ8tqEjvPs',
    appId: '1:309888173927:android:b77a560fc60e8239a511c2',
    messagingSenderId: '309888173927',
    projectId: 'tharu-bag-center',
    storageBucket: 'tharu-bag-center.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT5OzRxnrWuBEUuJ6L2dsRGWf1Y7N3l-Y',
    appId: '1:309888173927:ios:d87b0b7a1e445a35a511c2',
    messagingSenderId: '309888173927',
    projectId: 'tharu-bag-center',
    storageBucket: 'tharu-bag-center.firebasestorage.app',
    iosBundleId: 'com.example.myBagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT5OzRxnrWuBEUuJ6L2dsRGWf1Y7N3l-Y',
    appId: '1:309888173927:ios:d87b0b7a1e445a35a511c2',
    messagingSenderId: '309888173927',
    projectId: 'tharu-bag-center',
    storageBucket: 'tharu-bag-center.firebasestorage.app',
    iosBundleId: 'com.example.myBagApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Hob63kxbSkGLuIfT--SsiT-fwo4J-_M',
    appId: '1:309888173927:web:71720656b82016b4a511c2',
    messagingSenderId: '309888173927',
    projectId: 'tharu-bag-center',
    authDomain: 'tharu-bag-center.firebaseapp.com',
    storageBucket: 'tharu-bag-center.firebasestorage.app',
    measurementId: 'G-GEHZZKH4CQ',
  );
}
